### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-) I used search-and-replace across the entire project, so the `.html` files should contain exactly the same fixes as the `.Rmd` sources.

Thanks for sharing this lesson!

### CODE REVIEW

**Comment by dmi3kno** [comment]
Awesome! Thanks! Did you re-render htmls from Rmds?

**Comment by katrinleinweber** [comment]
No, because don't have the path `../Data/gapminder-FiveYearData.csv` on my computer ;-) That's why I searched and replaced across all files.

**Comment by dmi3kno** [comment]
I am terribly sorry about that. We were young and stupid and did not care
about reproducibility. It should work with gapminder <- gapminder::gapminder

**Comment by katrinleinweber** [comment]
I'm not sure how that solves the external folder problem, sorry. Haven't used the gapminder package before, though. But I noticed another possible improvement, see #2.

**Comment by katrinleinweber** [comment]
When re-`knit()`ing the `.Rmds`, the diffs become huge now anyway, because of binary blobs, CSS & JavaScript changes, that some `knitr` update probably introduced. They are far less reviewable than the `.html` changes in this PR, IMHO.

**Pull request merged**
